### ISSUE TITLE
用majiro-py导入的格式是sjis编码

### ISSUE THREAD

**Issue by YuriSizuku** [XHLin-gamer/anotaka-chinese-texts#3]
如题，要想中文显示要把编码改成gbk，游戏程序判断sjis范围也要修改。
这个项目包含这部分内容吗？没找到这块内容

**Comment by XHLin-gamer** [comment]
没有包含这部分内容。当时在游戏的exe中尝试找过相关的反汇编代码，但是最终没有找到。

**Comment by XHLin-gamer** [comment]
如果您有解决程序内编码转换的方法，请务必在告诉我。实话说这个坑已经很久没有推动了/(ㄒoㄒ)/~~

**Comment by YuriSizuku** [comment]
我之前写过[majirov3动态汉化](https://bbs.kanxue.com/thread-268508.htm)的教程，但是这种方法有些太过复杂了，通用性不太好，很多硬编码，换个游戏就要重新分析一下了。这种方法也仅供教程参考了。

我打算最近重新写个majiro引擎的通用汉化工具。

**Comment by XHLin-gamer** [comment]
thx

**Comment by YuriSizuku** [comment]
话说你有没有遇到过 "unexpected token during switch case" 报错 ？ 对于start.mjo等文件
https://github.com/trigger-segfault/majiro-py/issues/4

[sorairo_start.mjo.zip](https://github.com/XHLin-gamer/anotaka-chinese-texts/files/12330935/sorairo_start.mjo.zip)

**Comment by XHLin-gamer** [comment]
没有欸

**Comment by XHLin-gamer** [comment]
时间有些早了，记不太清楚了。印象里在majiro-py里需要注释掉某一行的raise exception，才能正常运行

**Comment by YuriSizuku** [comment]
折腾了几天终于把汉化弄好了，代码开源到 https://github.com/YuriSizuku/GalgameReverse/tree/master/src/majiro了。
这次算是弄出了比较通用的解决方案了。

![sorairo_chstest](https://github.com/XHLin-gamer/anotaka-chinese-texts/assets/15275959/01d5efac-9498-4e29-bf35-4ba912effd15)

这个引擎需要注意的几个问题：
1. 指令和文本都是用sjis，改成gbk后就会出问题，因此我对于文本手动[[cp932]], [[cp936]]进行区分。
2. 需要改exe，CreateFontIndirectA的charset改为0x86；_mbchr 需要修改 '「」', 0x8175 -> 0xa1b8, 0x8176 -> 0xa1b9，否则语音播放会出问题。
3. 各种乱码问题，exe里面有sjis和unicode文本，其他的分散在各个mjo、cfg、env里面。字体“ＭＳ　ゴシック”在sysdata.cfg里面
4. mjotool无法asm的部分，采取直接解密mjo并且在二进制文本上修改，详见我写的工具[majiro_mjo.py](https://github.com/YuriSizuku/GalgameReverse/blob/master/src/majiro/majiro_mjo.py). 
5. 图片部分可以直接加载png，不用再转换成rct和rc8格式了。

**Comment by XHLin-gamer** [comment]
thx
